
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install pytest flake8 black isort
      - name: Lint
        run: |
          black --check .
          isort --check-only .
          flake8 .
      - name: Test
        run: |
          pytest -q
